### ISSUE TITLE
visitorData generation sometimes fails

### ISSUE THREAD

**Issue by 404-Program-not-found** [VueTubeApp/VueTube-Extractor#4]
### Steps to reproduce

It would appear visitorData has a few complications and that not all randomly generated 11 character string is valid. This results in not so uncommon cases where the home page test fails despite everything else working as expected

### Expected behavior

home page tests should work all the time

### Actual behavior

sometimes home page tests fails with error: " No section contents"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have confirmed that this is an issue with VueTube **Extractor**, and not the main app.
- [X] I will fill out all of the requested information in this form.

**Comment by LuanRT** [comment]
I ran into this issue as well. It turns out not the random string, but the timestamp sometimes causes `toString('base64')` to add characters like `/` and `+` to the base64d buffer which are not supported by YouTube's base64 implementation ([RFC 4648](https://datatracker.ietf.org/doc/html/rfc4648#section-5)). There's `toString('base64url')` and it works, but unfortunately also removes `=`  from the string and that causes YouTube to reject the visitor data as well. The only solution I found (besides using the visitor data provided by `sw.js_data`) is to [manually replace](https://github.com/LuanRT/YouTube.js/blob/main/lib/proto/index.js#L16) those characters.
